
 create table bscit(name varchar(15),class varchar(7),rollno  varchar(7),address varchar(15);
 insert into  bscit values('Balasubramanim','B.Sc.IT','07IT126','Kossanam');
 insert into bscit values('Gopi','B.SC.IT','07IT127','Avanasi');
 insert into bscit values('Gughanand','B.Sc.IT','07IT128','Anthiyur');
 insert into bscit values('Gowtham','B.Sc.IT','07IT129','Mavani');
 insert into bscit values('Jayakumar','B.Sc.IT','07IT130','Pangalapudur');
 insert into bscit values('Karthick','B.Sc.IT','07IT131','Kavanthapadi');
 insert into bscit values('Karthikeyan','B.Sc.IT','07IT132','Nambiyur');
 insert into bscit values('Muthukumar','B.Sc.IT','07IT133','Nambiyur');
 insert into bscit values('Natesan','B.Sc.IT','07IT134','Oddathori');
 insert into bscit values('Poovannan','B.Sc.IT','07IT135','Thalavadi');
 insert into bscit values('Ramasamy','B.Sc.IT','07IT136','Kuramandhur');
 insert into bscit values('Ramkumar','B.Sc.IT','07IT137','Gobi');
 insert into bscit values('Rathinavel','B.Sc.IT','07IT138','Sathy');
 insert into bscit values('Ravichandar','B.Sc.IT','07IT139','Nambiyur');
 insert into bscit values('Satheesh','B.Sc.IT','07IT140','Kossanam');
 insert into bscit values('Senthilprabhu','B.Sc.IT','07IT141','Gobi');
 insert into bscit values('Sundharamoorthy','B.Sc.IT','07IT142','Nambiyur');
 insert into bscit values('Suresh','B.Sc.IT','07IT143','Nambiyur');
 insert into bscit values('Tamilarasan','B.Sc.IT','07IT144','Mavani');
 insert into bscit values('Thirumoorthy','B.Sc.IT','07IT145','Kadakampalayam');
 insert into bscit values('D.Vijayakumar','B.Sc.IT','07IT146','Nambiyur');
 insert into bscit values('P.L.Vijayakumar','B.Sc.IT','07IT147','Gobi');
 select * from bscit;
